export const userData = [
  {
    assignedUser: {
      id: 1,
      name: "Alice Johnson",
    },
    endsOn: "2024-03-15",
    client: {
      id: 1,
      name: "Client A",
    },
    project: {
      id: 1,
      name: "Project Alpha",
    },
    startsOn: "2024-01-08",
    status: "Actual",
    workWeeks: [
      {
        id: 1,
        actualHours: 8,
        estimatedHours: 10,
        assignmentId: 1,
        cweek: 1,
        year: 2024,
      },
      {
        id: 2,
        actualHours: 34,
        estimatedHours: 10,
        assignmentId: 1,
        cweek: 2,
        year: 2024,
      },
      {
        id: 3,
        actualHours: 2,
        estimatedHours: 10,
        assignmentId: 1,
        cweek: 3,
        year: 2024,
      },
      {
        id: 4,
        actualHours: 10,
        estimatedHours: 10,
        assignmentId: 1,
        cweek: 4,
        year: 2024,
      },
      {
        id: 5,
        actualHours: 11,
        estimatedHours: 10,
        assignmentId: 1,
        cweek: 5,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 10,
  },
  {
    assignedUser: {
      id: 2,
      name: "Bob Smith",
    },
    endsOn: "2024-04-20",
    client: {
      id: 2,
      name: "Client B",
    },
    project: {
      id: 2,
      name: "Project Beta",
    },
    startsOn: "2024-02-05",
    status: "Actual",
    workWeeks: [
      {
        id: 6,
        actualHours: 12,
        estimatedHours: 15,
        assignmentId: 2,
        cweek: 6,
        year: 2024,
      },
      {
        id: 7,
        actualHours: 14,
        estimatedHours: 15,
        assignmentId: 2,
        cweek: 7,
        year: 2024,
      },
      {
        id: 8,
        actualHours: 16,
        estimatedHours: 15,
        assignmentId: 2,
        cweek: 8,
        year: 2024,
      },
      {
        id: 9,
        actualHours: 18,
        estimatedHours: 15,
        assignmentId: 2,
        cweek: 9,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 15,
  },
  {
    assignedUser: {
      id: 3,
      name: "Carol White",
    },
    endsOn: "2024-06-30",
    client: {
      id: 3,
      name: "Client C",
    },
    project: {
      id: 3,
      name: "Project Gamma",
    },
    startsOn: "2024-03-01",
    status: "Actual",
    workWeeks: [
      {
        id: 10,
        actualHours: 20,
        estimatedHours: 25,
        assignmentId: 3,
        cweek: 10,
        year: 2024,
      },
      {
        id: 11,
        actualHours: 22,
        estimatedHours: 25,
        assignmentId: 3,
        cweek: 11,
        year: 2024,
      },
      {
        id: 12,
        actualHours: 24,
        estimatedHours: 25,
        assignmentId: 3,
        cweek: 12,
        year: 2024,
      },
      {
        id: 13,
        actualHours: 16,
        estimatedHours: 25,
        assignmentId: 3,
        cweek: 13,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 25,
  },
  {
    assignedUser: {
      id: 4,
      name: "David Brown",
    },
    endsOn: "2024-02-28",
    client: {
      id: 4,
      name: "Client D",
    },
    project: {
      id: 4,
      name: "Project Delta",
    },
    startsOn: "2024-01-15",
    status: "Actual",
    workWeeks: [
      {
        id: 14,
        actualHours: 25,
        estimatedHours: 20,
        assignmentId: 4,
        cweek: 31,
        year: 2024,
      },
      {
        id: 15,
        actualHours: 23,
        estimatedHours: 20,
        assignmentId: 4,
        cweek: 32,
        year: 2024,
      },
      {
        id: 16,
        actualHours: 20,
        estimatedHours: 20,
        assignmentId: 4,
        cweek: 5,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 20,
  },
  {
    assignedUser: {
      id: 5,
      name: "Emma Davis",
    },
    endsOn: "2024-05-31",
    client: {
      id: 5,
      name: "Client E",
    },
    project: {
      id: 5,
      name: "Project Epsilon",
    },
    startsOn: "2024-02-01",
    status: "Actual",
    workWeeks: [
      {
        id: 17,
        actualHours: 10,
        estimatedHours: 12,
        assignmentId: 5,
        cweek: 6,
        year: 2024,
      },
      {
        id: 18,
        actualHours: 11,
        estimatedHours: 12,
        assignmentId: 5,
        cweek: 7,
        year: 2024,
      },
      {
        id: 19,
        actualHours: 12,
        estimatedHours: 12,
        assignmentId: 5,
        cweek: 8,
        year: 2024,
      },
      {
        id: 20,
        actualHours: 13,
        estimatedHours: 12,
        assignmentId: 5,
        cweek: 9,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 12,
  },
  {
    assignedUser: {
      id: 6,
      name: "Frank Harris",
    },
    endsOn: "2024-07-15",
    client: {
      id: 6,
      name: "Client F",
    },
    project: {
      id: 6,
      name: "Project Zeta",
    },
    startsOn: "2024-03-15",
    status: "Actual",
    workWeeks: [
      {
        id: 21,
        actualHours: 14,
        estimatedHours: 18,
        assignmentId: 6,
        cweek: 30,
        year: 2024,
      },
      {
        id: 22,
        actualHours: 15,
        estimatedHours: 18,
        assignmentId: 6,
        cweek: 32,
        year: 2024,
      },
      {
        id: 23,
        actualHours: 16,
        estimatedHours: 18,
        assignmentId: 6,
        cweek: 33,
        year: 2024,
      },
      {
        id: 24,
        actualHours: 17,
        estimatedHours: 18,
        assignmentId: 6,
        cweek: 34,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 18,
  },
  {
    assignedUser: {
      id: 7,
      name: "Grace Lee",
    },
    endsOn: "2024-08-31",
    client: {
      id: 7,
      name: "Client G",
    },
    project: {
      id: 7,
      name: "Project Eta",
    },
    startsOn: "2024-04-01",
    status: "Actual",
    workWeeks: [
      {
        id: 25,
        actualHours: 29,
        estimatedHours: 20,
        assignmentId: 7,
        cweek: 14,
        year: 2024,
      },
      {
        id: 25,
        actualHours: 29,
        estimatedHours: 20,
        assignmentId: 7,
        cweek: 15,
        year: 2024,
      },
      {
        id: 25,
        actualHours: 29,
        estimatedHours: 20,
        assignmentId: 7,
        cweek: 16,
        year: 2024,
      },
      {
        id: 21,
        actualHours: 20,
        estimatedHours: 20,
        assignmentId: 7,
        cweek: 17,
        year: 2024,
      },
      {
        id: 27,
        actualHours: 31,
        estimatedHours: 20,
        assignmentId: 7,
        cweek: 18,
        year: 2024,
      },
    ],
    estimatedWeeklyHours: 20,
  },
];

// export const userData = [
//   {
//     assignedUser: {
//       id: 1,
//       name: "Alice Johnson",
//     },
//     endsOn: "2024-03-15",
//     client: {
//       id: 1,
//       name: "Client A",
//     },
//     project: {
//       id: 1,
//       name: "Project Alpha",
//     },
//     startsOn: "2024-01-08",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 1,
//         actualHours: 8,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 1,
//         year: 2024,
//       },
//       {
//         id: 2,
//         actualHours: 9,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 2,
//         year: 2024,
//       },
//       {
//         id: 3,
//         actualHours: 7,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 3,
//         year: 2024,
//       },
//       {
//         id: 4,
//         actualHours: 10,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 4,
//         year: 2024,
//       },
//       {
//         id: 5,
//         actualHours: 11,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 5,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 10,
//   },
//   {
//     assignedUser: {
//       id: 2,
//       name: "Bob Smith",
//     },
//     endsOn: "2024-04-20",
//     client: {
//       id: 2,
//       name: "Client B",
//     },
//     project: {
//       id: 2,
//       name: "Project Beta",
//     },
//     startsOn: "2024-02-05",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 6,
//         actualHours: 12,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 6,
//         year: 2024,
//       },
//       {
//         id: 7,
//         actualHours: 14,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 7,
//         year: 2024,
//       },
//       {
//         id: 8,
//         actualHours: 16,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 8,
//         year: 2024,
//       },
//       {
//         id: 9,
//         actualHours: 18,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 9,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 15,
//   },
//   {
//     assignedUser: {
//       id: 3,
//       name: "Carol White",
//     },
//     endsOn: "2024-06-30",
//     client: {
//       id: 3,
//       name: "Client C",
//     },
//     project: {
//       id: 3,
//       name: "Project Gamma",
//     },
//     startsOn: "2024-03-01",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 10,
//         actualHours: 20,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 10,
//         year: 2024,
//       },
//       {
//         id: 11,assignments.map(
//         actualHours: 22,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 11,
//         year: 2024,
//       },
//       {
//         id: 12,
//         actualHours: 24,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 12,
//         year: 2024,
//       },
//       {
//         id: 13,
//         actualHours: 26,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 13,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 25,
//   },
//   {
//     assignedUser: {
//       id: 4,
//       name: "David Brown",
//     },
//     endsOn: "2024-02-28",
//     client: {
//       id: 4,
//       name: "Client D",
//     },
//     project: {
//       id: 4,
//       name: "Project Delta",
//     },
//     startsOn: "2024-01-15",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 14,
//         actualHours: 15,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 3,
//         year: 2024,
//       },
//       {
//         id: 15,
//         actualHours: 18,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 4,
//         year: 2024,
//       },
//       {
//         id: 16,
//         actualHours: 20,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 5,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 20,
//   },
//   {
//     assignedUser: {
//       id: 1,
//       name: "Alice Johnson",
//     },
//     endsOn: "2024-03-15",
//     client: {
//       id: 1,
//       name: "Client A",
//     },
//     project: {
//       id: 1,
//       name: "Project Alpha",
//     },
//     startsOn: "2024-01-08",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 1,
//         actualHours: 8,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 1,
//         year: 2024,
//       },
//       {
//         id: 2,
//         actualHours: 9,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 2,
//         year: 2024,
//       },
//       {
//         id: 3,
//         actualHours: 7,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 3,
//         year: 2024,
//       },
//       {
//         id: 4,
//         actualHours: 10,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 4,
//         year: 2024,
//       },
//       {
//         id: 5,
//         actualHours: 11,
//         estimatedHours: 10,
//         assignmentId: 1,
//         cweek: 5,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 10,
//   },
//   {
//     assignedUser: {
//       id: 2,
//       name: "Bob Smith",
//     },
//     endsOn: "2024-04-20",
//     client: {
//       id: 2,
//       name: "Client B",
//     },
//     project: {
//       id: 2,
//       name: "Project Beta",
//     },
//     startsOn: "2024-02-05",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 6,
//         actualHours: 12,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 6,
//         year: 2024,
//       },
//       {
//         id: 7,
//         actualHours: 14,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 7,
//         year: 2024,
//       },
//       {
//         id: 8,
//         actualHours: 16,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 8,
//         year: 2024,
//       },
//       {
//         id: 9,
//         actualHours: 18,
//         estimatedHours: 15,
//         assignmentId: 2,
//         cweek: 9,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 15,
//   },
//   {
//     assignedUser: {
//       id: 3,
//       name: "Carol White",
//     },
//     endsOn: "2024-06-30",
//     client: {
//       id: 3,
//       name: "Client C",
//     },
//     project: {
//       id: 3,
//       name: "Project Gamma",
//     },
//     startsOn: "2024-03-01",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 10,
//         actualHours: 20,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 10,
//         year: 2024,
//       },
//       {
//         id: 11,
//         actualHours: 22,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 11,
//         year: 2024,
//       },
//       {
//         id: 12,
//         actualHours: 24,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 12,
//         year: 2024,
//       },
//       {
//         id: 13,
//         actualHours: 26,
//         estimatedHours: 25,
//         assignmentId: 3,
//         cweek: 13,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 25,
//   },
//   {
//     assignedUser: {
//       id: 4,
//       name: "David Brown",
//     },
//     endsOn: "2024-02-28",
//     client: {
//       id: 4,
//       name: "Client D",
//     },
//     project: {
//       id: 4,
//       name: "Project Delta",
//     },
//     startsOn: "2024-01-15",
//     status: "Actual",
//     workWeeks: [
//       {
//         id: 14,
//         actualHours: 15,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 3,
//         year: 2024,
//       },
//       {
//         id: 15,
//         actualHours: 18,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 4,
//         year: 2024,
//       },
//       {
//         id: 16,
//         actualHours: 20,
//         estimatedHours: 20,
//         assignmentId: 4,
//         cweek: 5,
//         year: 2024,
//       },
//     ],
//     estimatedWeeklyHours: 20,
//   },
// ];
